from car import Car, ElectricCar, Battery

import time
time.sleep(2)
print("Hello, this is a simple representation of storing vehicle data by BlombergSoftware.")
time.sleep(4)
response_one = input("\nWhat is the make of your vehicle: ")
time.sleep(2)
response_two = input("What is the model of your vehicle: ")
time.sleep(2)
response_three = input("What is the year of your vehicle: ")
my_car = Car(response_one,response_two,response_three)
desc_my_car = my_car.get_descriptive_name()
print("Your car is a " + desc_my_car)
my_car.update_odometer(230000)
my_car.read_odometer()
print("\n")
time.sleep(2)
print("Now, lets try an electric vehicle...")
time.sleep(4)
eresponse_one = input("What is the make of your electric vehicle: ")
time.sleep(2)
eresponse_two = input("What is the model of your electric vehicle: ")
time.sleep(2)
eresponse_three = input("What is the year of your electric vehicle: ")
my_tesla = ElectricCar(eresponse_one,eresponse_two, eresponse_three)
print("Your car is a " + str(my_tesla.get_descriptive_name()) + ".")
my_tesla.read_odometer()
my_tesla.battery.describe_battery()
my_tesla.battery.get_range()
print("\nThank you for your participation in BlombergSoftware.")
